# Generated by Django 4.2.19 on 2025-02-11 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the menu item (minimum 2 characters).', max_length=80, validators=[django.core.validators.MinLengthValidator(2)])),
                ('price', models.BigIntegerField(help_text='Price of the item in decimal format.')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount as a decimal value (e.g., 0.15 for 15%).', max_digits=4, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the menu item.')),
                ('serving_time_start', models.TimeField()),
                ('serving_time_end', models.TimeField()),
                ('estimated_cooking_time', models.CharField(choices=[('10 min', '10 min'), ('20 min', '20 min'), ('30 min', '30 min')], default='null', help_text='Estimated time to prepare the dish.', max_length=50)),
                ('entity', models.SmallIntegerField(help_text='Number of items available.')),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu_items.category')),
            ],
        ),
    ]
